/**
 * Prints INSERT statements for the supply directory from the checked-in
 * reference data, so a fresh Supabase project can be bootstrapped with the
 * same rows the local development store uses.
 *
 *   npm run seed:sql > supabase/seed.generated.sql
 */

import {
  DOCTOR_SEEDS,
  HOSPITAL_SEEDS,
  TREATMENTS_WITH_COSTS,
} from "../src/lib/reference-data.ts";

const q = (value: string | null) =>
  value === null ? "null" : `'${value.replace(/'/g, "''")}'`;

const textArray = (values: string[]) =>
  `array[${values.map((value) => q(value)).join(", ")}]::text[]`;

const lines: string[] = [
  "-- Generated by scripts/generate-seed-sql.ts. Do not edit by hand.",
  "-- Illustrative sample supply data; replace with vetted listings via Admin > Supply CMS.",
  "",
  "begin;",
  "",
];

lines.push(
  "insert into public.treatments (name, slug, category, description, overview, stay_summary, indicative_cost_min, indicative_cost_max, home_country_reference_costs) values",
);
lines.push(
  TREATMENTS_WITH_COSTS.map(
    (treatment) =>
      `  (${q(treatment.name)}, ${q(treatment.slug)}, ${q(treatment.category)}, ${q(
        treatment.description,
      )}, ${q(treatment.overview)}, ${q(treatment.stay_summary)}, ${
        treatment.indicative_cost_min
      }, ${treatment.indicative_cost_max}, ${q(
        JSON.stringify(treatment.home_country_reference_costs),
      )}::jsonb)`,
  ).join(",\n") + "\non conflict (slug) do nothing;",
);
lines.push("");

lines.push(
  "insert into public.hospitals (name, slug, city, accreditation, specialties, about, facilities, beds, established_year, intl_desk_contact, treatment_slugs) values",
);
lines.push(
  HOSPITAL_SEEDS.map(
    (hospital) =>
      `  (${q(hospital.name)}, ${q(hospital.slug)}, ${q(hospital.city)}, ${textArray(
        hospital.accreditation,
      )}, ${textArray(hospital.specialties)}, ${q(hospital.about)}, ${textArray(
        hospital.facilities,
      )}, ${hospital.beds}, ${hospital.established_year}, ${q(
        hospital.intl_desk_contact,
      )}, ${textArray(hospital.treatment_slugs)})`,
  ).join(",\n") + "\non conflict (slug) do nothing;",
);
lines.push("");

lines.push(
  "insert into public.doctors (hospital_id, name, specialty, qualifications, years_experience)",
);
lines.push("select h.id, d.name, d.specialty, d.qualifications, d.years_experience");
lines.push("from (values");
lines.push(
  DOCTOR_SEEDS.map(
    (doctor) =>
      `  (${q(doctor.hospital_slug)}, ${q(doctor.name)}, ${q(doctor.specialty)}, ${q(
        doctor.qualifications,
      )}, ${doctor.years_experience})`,
  ).join(",\n"),
);
lines.push(
  ") as d(hospital_slug, name, specialty, qualifications, years_experience)",
);
lines.push("join public.hospitals h on h.slug = d.hospital_slug;");
lines.push("");
lines.push("commit;");

process.stdout.write(lines.join("\n") + "\n");
